In [1]:
import numpy as np
a = [[7, 9, 9, 8], [8, 7, 8, 7], [9, 6, 8, 9], [6, 7, 8, 6]]
w = [0.1, 0.4, 0.3, 0.2]
I = [1, 1, 1, 0]


In [2]:
r=np.zeros([np.size(a,0),np.size(a,1)])
for i in range(0,np.size(a,0)):
    for j in range(0,np.size(a,1)):
        r[i][j]=a[i][j]/np.sqrt(np.sum(np.power(a,2),axis=0)[j])*w[j]
# r

In [3]:
Ap=np.zeros([np.size(r,1)])
An=np.zeros([np.size(r,1)])
for i in range(0,np.size(r,1)):
    if I[i]==1:
        Ap[i]=[max(j) for j in zip(*r)][i]
        An[i]=[min(j) for j in zip(*r)][i]
    elif I[i]==0:
        Ap[i]=[min(j) for j in zip(*r)][i]
        An[i]=[max(j) for j in zip(*r)][i]
# print(Ap)
# print(An)

In [4]:
Sp=np.zeros([np.size(a,0),np.size(a,1)])
Sn=np.zeros([np.size(a,0),np.size(a,1)])
for i in range(0,np.size(a,0)):
    for j in range(0,np.size(a,1)):
        Sp[i][j]=np.power(r[i][j]-Ap[j],2)
        Sn[i][j]=np.power(r[i][j]-An[j],2)
Sp=np.power(np.sum(Sp,axis=1),.5)
Sn=np.power(np.sum(Sn,axis=1),.5)


In [5]:
C=np.zeros(np.size(Sp))
for i in range(0,np.size(Sp)):
    C[i]=Sn[i]/(Sp[i]+Sn[i])

print('the best alternaitve is: '+ str(C.argmax(axis=0)+1))
print('the worse alternaitve is: '+ str(C.argmin(axis=0)+1))

the best alternaitve is: 1
the worse alternaitve is: 3


In [17]:
# An=np.zeros([4])
# An
# r.max(axis=0)
# res = [max(i) for i in zip(*r)][1] 
print(r)
print(list(zip(*r))[0])

[[0.04615663 0.24551796 0.16341143 0.10550088]
 [0.05275044 0.19095842 0.14525461 0.09231327]
 [0.05934424 0.16367864 0.14525461 0.11868849]
 [0.03956283 0.19095842 0.14525461 0.07912566]]
(0.04615663313770509, 0.05275043787166296, 0.05934424260562084, 0.039562828403747224)
